// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV-g-zjd-cU1EyBWRUA4Sn3r2iTe_DU6c',
    appId: '1:412126387398:web:6497a4701c18d708080bc7',
    messagingSenderId: '412126387398',
    projectId: 'urdudataset-rcet-cs-21',
    authDomain: 'urdudataset-rcet-cs-21.firebaseapp.com',
    storageBucket: 'urdudataset-rcet-cs-21.firebasestorage.app',
    measurementId: 'G-CWQEN03EQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl7cyO9gpUGs5xnn7Hm04VAdd3ZTFkh0Q',
    appId: '1:412126387398:android:da7eb7370e464703080bc7',
    messagingSenderId: '412126387398',
    projectId: 'urdudataset-rcet-cs-21',
    storageBucket: 'urdudataset-rcet-cs-21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBglsSSB0mAf3lSexs3Me1pIFd5iQDFaj8',
    appId: '1:412126387398:ios:604f077e3317e1a3080bc7',
    messagingSenderId: '412126387398',
    projectId: 'urdudataset-rcet-cs-21',
    storageBucket: 'urdudataset-rcet-cs-21.firebasestorage.app',
    iosBundleId: 'com.example.urdudatasetcollection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBglsSSB0mAf3lSexs3Me1pIFd5iQDFaj8',
    appId: '1:412126387398:ios:604f077e3317e1a3080bc7',
    messagingSenderId: '412126387398',
    projectId: 'urdudataset-rcet-cs-21',
    storageBucket: 'urdudataset-rcet-cs-21.firebasestorage.app',
    iosBundleId: 'com.example.urdudatasetcollection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV-g-zjd-cU1EyBWRUA4Sn3r2iTe_DU6c',
    appId: '1:412126387398:web:8a5397eee75d310f080bc7',
    messagingSenderId: '412126387398',
    projectId: 'urdudataset-rcet-cs-21',
    authDomain: 'urdudataset-rcet-cs-21.firebaseapp.com',
    storageBucket: 'urdudataset-rcet-cs-21.firebasestorage.app',
    measurementId: 'G-NS70ZJZJQC',
  );
}
